Image api
CSPCLAB/cspc_apply_server pull request #28
Opened 2024-02-19 14:43 UTC by YSHyeonn

2024-02-19 14:49 UTC, ljy2855 requested changes
해당 code review 반영해서 push해

2024-02-19 14:49 UTC, ljy2855 commented on app/image/models.py
> +class Apply_Image(models.Model):
* 불필요한 모델들 모두 하나로 합치고 admin page에도 하나에서 관리하도록 변경해줘
*  필요한 image는 여러 개의 값을 못 가지도록 1대1로 제한하게 변경

2024-02-19 14:49 UTC, ljy2855 commented on app/image/views.py
> +from rest_framework.parsers import MultiPartParser, FormParser
views.py도 안쓰면 지워

2024-02-19 14:49 UTC, ljy2855 commented on app/image/urls.py
> +# from django.urls import path
이것도 지워

2024-02-19 14:49 UTC, ljy2855 commented on app/image/serializers.py
> +from rest_framework import serializers
이것도 안쓰지 않아? 지워

2024-02-19 14:49 UTC, ljy2855 commented on app/swagger_response.py
> +
지워

2024-02-19 14:49 UTC, ljy2855 commented on app/image/admin.py
> +from django.contrib import admin
여기도 모델 하나만 등록해

2024-02-19 16:26 UTC, YSHyeonn commented on app/image/models.py
> +class Apply_Image(models.Model):
불필요하기 보다는 프론트에서 쓰는 페이지별로 이미지 관리하기 편하게 했던건데 그냥 하나 모델로 해서 관리해?

2024-02-19 16:42 UTC, YSHyeonn commented on app/image/models.py
> +class Apply_Image(models.Model):
그 프론트에서 관리하기 쉽게 나누어져 있는 5개 페이지대로 model 만들었던건데 하나로 합병할까 그냥?

2024-02-20 13:54 UTC, ljy2855 commented on app/image/utils.py
> +    ext = filename.split(".")[-1]
admin page에서 파일 업로드했을때 실제 파일 어느식으로 저장돼?

2024-02-20 13:54 UTC, ljy2855 approved these changes

2024-02-20 13:55 UTC, merged